openrouter_manager/__init__.py,sha256=LNFfEfBYuZrAueJLfqfFytdWZitequ23Wo31roMVQTA,589
openrouter_manager/adapter/ai_agent.py,sha256=W-tzGiqnK-1aCTtO_KB-nqWb8FC3UexbhvhjmEoOROk,5215
openrouter_manager/adapter/llm_exception.py,sha256=9ezVCmN7-FFn4t_EVhh1ne1CXIt_dTRUuYeKRD-DpcM,255
openrouter_manager/adapter/prompt.py,sha256=AhIbDn2y6-xqx4wLx_8zQNpKbrDd6ZbxX4gg5D45fSo,748
openrouter_manager/adapter/variable.py,sha256=hSSDORgIiHnQnf1rUZG4VDnR-oY7esdYnWJRfua2rP4,117
openrouter_manager-0.0.3.dist-info/licenses/LICENSE.txt,sha256=YNO1ZtHyD2LDwS8XOgaaRKXWixM-I16c29MuGrCcT48,1079
openrouter_manager-0.0.3.dist-info/METADATA,sha256=tnQ2dT0ch-Q4HWO2kO8n52wvgY5w0vYhoYxlh0mfAyk,5266
openrouter_manager-0.0.3.dist-info/WHEEL,sha256=JNWh1Fm1UdwIQV075glCn4MVuCRs0sotJIq-J6rbxCU,109
openrouter_manager-0.0.3.dist-info/top_level.txt,sha256=KRRyn1OM887c-6897P77Pwc0IMR4QsLEMuvalub-H5w,19
openrouter_manager-0.0.3.dist-info/RECORD,,
